# Generated by Django 2.1.3 on 2019-07-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=30)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.AddIndex(
            model_name='picturesubmission',
            index=models.Index(fields=['User', 'Date'], name='emotions_pi_User_1d457d_idx'),
        ),
    ]
