# Generated by Django 2.1.3 on 2019-08-27 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emotions', '0002_auto_20190729_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Topic', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='picturesubmission',
            name='emotions_pi_User_1d457d_idx',
        ),
        migrations.AlterField(
            model_name='picturesubmission',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videosubmission',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='picturesubmission',
            index=models.Index(fields=['User', 'Date'], name='emotions_pi_User_id_a193d2_idx'),
        ),
        migrations.AddField(
            model_name='thread',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotions.Thread'),
        ),
        migrations.AddField(
            model_name='comment',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
